# This Dockerfile is to build a docker image of a toy BIDS App for testing BABS. 
# The function is to count the number of images in a BIDS dataset

FROM alpine:3.16

# install bash:
RUN apk add --no-cache --upgrade bash

# install python and pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

ENV PYTHONPATH=""

COPY toy_command.py /toy_command.py
RUN chmod +x /toy_command.py
ENTRYPOINT ["/toy_command.py"]
